# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 763f93edbf537926ceefe2d9c9dc77287c879cfa43c6242f36c2c0e25941b30bf3e1bbe4702a4e4763c18e32273553b2dc877a39b14ad88d6ef66a257e0b6614

test:
  secret_key_base: 110f83ab6bf56bd15665665ff31f93a196e9eb5b831f3a5e7cc862a5386ec842b2e0bb2e11f103bb6e0441e5242ebeb46ed2bf758e8768526f69215e125cac64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
